apiVersion : apps/v1
kind: Deployment
metadata:
  name: microservices 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservices
  template:
    metadata:
      labels:
        app: microservices 
    spec:
      containers:
        - name: microservices 
          image: us-central1-docker.pkg.dev/carbon-zone-445515-b4/microservices/microservices:task
          ports:
          - containerPort: 5000