apiVersion: v1
kind: Service
metadata:
    name: microservices
    labels:
      app: microservices
spec:
    type: LoadBalancer
    ports:
    - port: 5000 
      targetPort: 5000
    selector:
        app: microservices
